AWSTemplateFormatVersion: '2010-09-09'
Description: Regional observability baseline StackSet.

Resources:
  AlertsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: regional-network-observability
